spring:
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: audit
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer